# Use official Node image
FROM node:18

# Create app folder inside container
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Expose port
EXPOSE 5000

# Start server
CMD ["node", "index.js"]


