name: Run Monitor Script

on: [push]

jobs:
  run-scrip:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Make script executable
       run: chmod +x monitor.sh

     - name: Run script
       run: ./monitor.sh
